Repository adventuregamestudio/ags, pull requests merged in 2019-07, with the labels that each got.

#852 Add ID property to AudioClip
  Common/ac/dynobj/scriptaudioclip.h
  Editor/AGS.Editor/AGSEditor.cs
  Editor/AGS.Editor/Components/AudioComponent.cs
  Editor/AGS.Editor/DataFileWriter.cs
  Editor/AGS.Editor/Resources/agsdefns.sh
  Editor/AGS.Editor/Tasks.cs
  Editor/AGS.Types/AudioClip.cs
  Editor/AGS.Types/Game.cs
  Editor/AGS.Types/PropertyGridExtras/AudioClipTypeConverter.cs
  Editor/AGS.Types/Settings.cs
  Engine/ac/audioclip.cpp
  Engine/game/game_init.cpp
Labels: pull: under review

#840 AGS 3.5.0 - macos - Add support and documentation for embedding resources
  Engine/CMakeLists.txt
  OSX/README.md
  OSX/Resources/ac2game.dat
  OSX/Resources/acsetup.cfg
  OSX/Resources/ags.icns
  OSX/Resources/audio.vox
  OSX/Resources/speech.vox
  OSX/ags.iconset/icon_128x128.png
  OSX/ags.iconset/icon_128x128@2x.png
  OSX/ags.iconset/icon_16x16.png
  OSX/ags.iconset/icon_16x16@2x.png
  OSX/ags.iconset/icon_256x256.png
  OSX/ags.iconset/icon_256x256@2x.png
  OSX/ags.iconset/icon_32x32.png
  OSX/ags.iconset/icon_32x32@2x.png
  OSX/ags.iconset/icon_512x512.png
  OSX/ags.iconset/icon_512x512@2x.png
Labels: ags3

#859 3.5.0: made String::Split also return first and last empty segment
  Common/util/string.cpp
  Common/util/string.h
  Engine/test/test_string.cpp
Labels: ags3, pull: under review

#858 3.5.0: Allow to change certain game item IDs in Editor
  Editor/AGS.Editor/AGSEditor.csproj
  Editor/AGS.Editor/Components/AudioComponent.cs
  Editor/AGS.Editor/Components/CharactersComponent.cs
  Editor/AGS.Editor/Components/DialogsComponent.cs
  Editor/AGS.Editor/Components/GuiComponent.cs
  Editor/AGS.Editor/Components/InventoryComponent.cs
  Editor/AGS.Editor/Components/ViewsComponent.cs
  Editor/AGS.Editor/GUI/GUIController.cs
  Editor/AGS.Editor/GUI/NumberEntryWithInfoDialog.Designer.cs
  Editor/AGS.Editor/GUI/NumberEntryWithInfoDialog.cs
  Editor/AGS.Editor/GUI/NumberEntryWithInfoDialog.resx
  Editor/AGS.Editor/Panes/SpriteSelector.cs
  Editor/AGS.Types/Game.cs
Labels: ags3, editor, pull: under review
