Repository adventuregamestudio/ags, pull requests merged in 2019-09, with the labels that each got.

#910 In Global Variables pane gather list of types from script header
  Editor/AGS.Editor/AGSEditor.csproj
  Editor/AGS.Editor/GUI/GlobalVariableDialog.cs
  Editor/AGS.Editor/Panes/GlobalVariablesEditor.cs
  Editor/AGS.Editor/Resources/agsdefns.sh
  Editor/AGS.Editor/TextProcessing/APITypeDef.cs
Labels: pull: under review

#906 Editor: explicitly update room document's property list on character add/removal
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
  Editor/AGS.Types/EditorFeatures/ContentDocument.cs
  Editor/AGS.Types/EditorFeatures/EditorContentPanel.cs
Labels: editor, pull: under review

#912 Editor: send mouse events only to active room layer
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/EdgesEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/EmptyEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/IRoomEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/WalkBehindsEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
Labels: pull: under review

#915 Use FillRectangle and RectangleF to draw room edges
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/EdgesEditorFilter.cs
Labels: ags3, editor

#911 Removed arbitrary limits in the text wrapping
  Common/font/fonts.cpp
  Common/font/fonts.h
  Common/gui/guidefines.h
  Common/gui/guilabel.cpp
  Common/gui/guilabel.h
  Common/gui/guimain.h
  Common/util/string.cpp
  Common/util/string.h
  Common/util/string_utils.cpp
  Common/util/string_utils.h
  Editor/Native/acgui_agsnative.cpp
  Engine/ac/dialog.cpp
  Engine/ac/display.cpp
  Engine/ac/drawingsurface.cpp
  Engine/ac/global_drawingsurface.cpp
  Engine/ac/global_gui.cpp
  Engine/ac/string.cpp
  Engine/ac/string.h
  Engine/gui/gui_engine.cpp
  Engine/gui/mylabel.cpp
  Engine/plugin/agsplugin.cpp
Labels: pull: under review

#916 Editor: disable sending data to ags server
  Editor/AGS.Editor/ApplicationController.cs
  Editor/AGS.Editor/GUI/ExceptionDialog.Designer.cs
  Editor/AGS.Editor/GUI/ExceptionDialog.resx
  Editor/AGS.Editor/GUI/PreferencesEditor.Designer.cs
Labels: editor

#929 Script API: added "frame" parameter to Character.Animate and Object.Animate
  Editor/AGS.Editor/Resources/agsdefns.sh
  Engine/ac/character.cpp
  Engine/ac/character.h
  Engine/ac/global_object.cpp
  Engine/ac/global_object.h
  Engine/ac/object.cpp
Labels: context: script api, type: enhancement

#934 AGS3.5 Key mapping refactor and some macos key bugs
  Engine/ac/global_game.cpp
  Engine/ac/keycode.h
  Engine/ac/sys_events.cpp
  Engine/device/mousew32.cpp
  Engine/main/game_run.cpp
Labels: ags3, pull: under review
