Repository adventuregamestudio/ags, pull requests merged in 2019-04, with the labels that each got.

#696 Script API: implemented PlayVoiceClip function
  Editor/AGS.Editor/Resources/agsdefns.sh
  Engine/ac/audiochannel.cpp
  Engine/ac/character.cpp
  Engine/ac/characterinfo_engine.cpp
  Engine/ac/display.cpp
  Engine/ac/display.h
  Engine/ac/game.cpp
  Engine/ac/gamestate.cpp
  Engine/ac/gamestate.h
  Engine/ac/global_api.cpp
  Engine/ac/global_audio.cpp
  Engine/ac/global_audio.h
  Engine/game/savegame_components.cpp
  Engine/main/engine.cpp
  Engine/main/update.cpp
  Engine/media/audio/audio.cpp
  Engine/plugin/agsplugin.cpp
  Engine/script/script_api.h
Labels: ags3, pull: under review, script api

#703 AGS3: Add CMake as an optional build system.
  CMAKE.md
  CMake/CheckFseeko.cmake
  CMake/CheckLoadMidiPf.cmake
  CMake/FindAllegro.cmake
  CMake/FindDirectX.cmake
  CMake/FindOgg.cmake
  CMake/FindTheora.cmake
  CMake/FindVorbis.cmake
  CMakeLists.txt
  Common/CMakeLists.txt
  Common/libsrc/aastr-0.1.1/CMakeLists.txt
  Engine/CMakeLists.txt
  Engine/libsrc/alfont-2.0.9/CMakeLists.txt
  Engine/libsrc/alfont-2.0.9/alfont.h
  Engine/libsrc/alfont-2.0.9/alfontdll.h
  Engine/libsrc/almp3-2.0.5/CMakeLists.txt
  Engine/libsrc/almp3-2.0.5/include/almp3.h
  Engine/libsrc/almp3-2.0.5/include/almp3dll.h
  Engine/libsrc/almp3-2.0.5/src/almp3.c
  Engine/libsrc/alogg/CMakeLists.txt
  Engine/libsrc/alogg/alogg.h
  Engine/libsrc/alogg/aloggdll.h
  Engine/libsrc/apeg-1.2.1/CMakeLists.txt
  Engine/libsrc/apeg-1.2.1/apeg.h
  Engine/libsrc/apeg-1.2.1/common.h
  Engine/libsrc/apeg-1.2.1/getbits.h
  Engine/libsrc/apeg-1.2.1/getblk.h
  Engine/libsrc/apeg-1.2.1/huffman.h
  Engine/libsrc/apeg-1.2.1/l2tables.h
  Engine/libsrc/apeg-1.2.1/mpeg1dec.h
  Engine/libsrc/apeg-1.2.1/mpg123.h
  Engine/libsrc/dumb-0.9.2/CMakeLists.txt
  Engine/libsrc/dumb-0.9.2/include/aldumb.h
  Engine/libsrc/dumb-0.9.2/include/dumb.h
  Engine/libsrc/dumb-0.9.2/include/internal/aldumb.h
  Engine/libsrc/dumb-0.9.2/include/internal/dumb.h
  Engine/libsrc/dumb-0.9.2/include/internal/it.h
  Engine/libsrc/freetype-2.1.3/CMakeLists.txt
  Engine/libsrc/glad/CMakeLists.txt
  Engine/libsrc/hq2x/CMakeLists.txt
  Engine/libsrc/hq2x/hq2x3x.h
  Engine/libsrc/libcda-0.5/CMakeLists.txt
Labels: ags3

#719 AGS3 engine: Use errno.h on all systems
  Engine/main/engine.cpp
Labels: ags3

#720 AGS3 Commonlib: remove support for older compilers
  Common/core/types.h
  Common/util/stdtr1compat.h
Labels: ags3

#716 AGS3 Further cmake work
  CMAKE.md
  CMake/FetchAllegro.cmake
  CMake/FetchOgg.cmake
  CMake/FetchTheora.cmake
  CMake/FetchVorbis.cmake
  CMake/c_flag_overrides.cmake
  CMake/cxx_flag_overrides.cmake
  CMakeLists.txt
  Common/CMakeLists.txt
  Common/libsrc/allegro4/CMakeLists.txt
  Engine/CMakeLists.txt
  Engine/libsrc/apeg-1.2.1/CMakeLists.txt
  Engine/libsrc/ogg/CMakeLists.txt
  Engine/libsrc/theora/CMakeLists.txt
  Engine/libsrc/vorbis/CMakeLists.txt
Labels: ags3

#714 Script API: string Set and Dictionary types
  Common/debug/debugmanager.h
  Common/game/customproperties.h
  Common/util/string.h
  Common/util/string_types.h
  Editor/AGS.Editor/Resources/agsdefns.sh
  Engine/ac/dynobj/cc_dynamicarray.cpp
  Engine/ac/dynobj/cc_dynamicarray.h
  Engine/ac/dynobj/cc_dynamicobject.h
  Engine/ac/dynobj/managedobjectpool.h
  Engine/ac/dynobj/scriptdict.cpp
  Engine/ac/dynobj/scriptdict.h
  Engine/ac/dynobj/scriptset.cpp
  Engine/ac/dynobj/scriptset.h
  Engine/ac/dynobj/scriptstring.cpp
  Engine/ac/dynobj/scriptstring.h
  Engine/ac/scriptcontainers.cpp
  Engine/ac/string.cpp
  Engine/ac/string.h
  Engine/script/cc_instance.cpp
  Engine/script/exports.cpp
  Engine/script/script_api.h
  Solutions/Engine.App/Engine.App.vcxproj
  Solutions/Engine.App/Engine.App.vcxproj.filters
Labels: ags3

#737 Uniform audio config option which supports string driver ID
  Editor/AGS.Editor/AGSEditor.cs
  Engine/ac/global_debug.cpp
  Engine/ac/runtime_defines.h
  Engine/main/config.cpp
  Engine/main/config.h
  Engine/main/engine.cpp
  Engine/main/quit.cpp
  Engine/media/audio/audio.cpp
  Engine/platform/windows/acplwin.cpp
  Engine/platform/windows/setup/winsetup.cpp
  Engine/plugin/agsplugin.cpp
Labels: ags3, pull: under review

#725 AGS 3: support for multiple cameras and viewports
  Editor/AGS.Editor/Resources/agsdefns.sh
  Engine/ac/display.cpp
  Engine/ac/draw.cpp
  Engine/ac/draw.h
  Engine/ac/draw_software.cpp
  Engine/ac/draw_software.h
  Engine/ac/dynobj/cc_dynamicobject.cpp
  Engine/ac/dynobj/cc_serializer.cpp
  Engine/ac/dynobj/scriptcamera.cpp
  Engine/ac/dynobj/scriptcamera.h
  Engine/ac/dynobj/scriptviewport.cpp
  Engine/ac/dynobj/scriptviewport.h
  Engine/ac/game.cpp
  Engine/ac/gamestate.cpp
  Engine/ac/gamestate.h
  Engine/ac/global_debug.cpp
  Engine/ac/global_screen.cpp
  Engine/ac/global_viewport.cpp
  Engine/ac/room.cpp
  Engine/ac/screen.cpp
  Engine/ac/viewport_script.cpp
  Engine/game/game_init.cpp
  Engine/game/savegame.cpp
  Engine/game/savegame_components.cpp
  Engine/game/savegame_internal.h
  Engine/game/viewport.cpp
  Engine/game/viewport.h
  Engine/main/engine.cpp
  Engine/main/engine_setup.cpp
  Engine/main/game_run.cpp
  Engine/plugin/agsplugin.cpp
  Solutions/Engine.App/Engine.App.vcxproj
  Solutions/Engine.App/Engine.App.vcxproj.filters
Labels: ags3, pull: under review
