Repository adventuregamestudio/ags, pull requests merged in 2019-02, with the labels that each got.

#603 Disable DRI3 in Linux launch wrapper
  Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs
  debian/ags+libraries/startgame
Labels: ags3, graphics, system: linux

#605 Added an error msg if NDK_HOME is undefined.
  Android/buildlibs/makestandalones.sh
Labels: system: android

#606 Add WFN font import
  Editor/AGS.Editor/Panes/FontEditor.cs
  Editor/AGS.Types/Constants.cs
Labels: ags3, editor

#608 Create .travis.yml for building AGS Engine on Linux
  .travis.yml
Labels: deployment

#634 AGS 3: fix reading GUIs in pre-3.4.0 games
  Common/gui/guimain.cpp
Labels: pull: reviewed

#621 AGS 3: ammendments to custom viewports system
  Common/ac/gamestructdefines.h
  Editor/AGS.Editor/Resources/agsdefns.sh
  Engine/ac/character.cpp
  Engine/ac/character.h
  Engine/ac/display.cpp
  Engine/ac/draw.cpp
  Engine/ac/game.cpp
  Engine/ac/gamestate.cpp
  Engine/ac/gamestate.h
  Engine/ac/global_api.cpp
  Engine/ac/global_character.cpp
  Engine/ac/global_character.h
  Engine/ac/global_game.cpp
  Engine/ac/global_game.h
  Engine/ac/global_hotspot.cpp
  Engine/ac/global_hotspot.h
  Engine/ac/global_object.cpp
  Engine/ac/global_object.h
  Engine/ac/global_region.cpp
  Engine/ac/global_region.h
  Engine/ac/global_walkablearea.cpp
  Engine/ac/global_walkablearea.h
  Engine/ac/hotspot.cpp
  Engine/ac/hotspot.h
  Engine/ac/object.cpp
  Engine/ac/object.h
  Engine/ac/region.cpp
  Engine/ac/region.h
  Engine/ac/room.cpp
  Engine/ac/screen.cpp
  Engine/ac/viewport.cpp
  Engine/main/game_run.cpp
  Engine/plugin/agsplugin.cpp
  Engine/plugin/agsplugin.h
Labels: ags3, script api

#630 Fix type casting warnings
  Common/ac/spritecache.cpp
  Common/ac/spritecache.h
  Common/font/wfnfont.cpp
  Common/font/wfnfont.h
  Common/util/memory.h
  Engine/ac/datetime.cpp
  Engine/ac/global_datetime.cpp
  Engine/ac/global_translation.cpp
  Engine/gfx/ali3dsw.cpp
  Engine/platform/windows/gfx/ali3dd3d.cpp
  Engine/plugin/agsplugin.cpp
  Engine/plugin/plugin_engine.h
  Engine/script/cc_instance.cpp
  Engine/test/test_inifile.cpp
Labels: ags3

#631 Simplified script interpreter's Math implementations
  Engine/ac/math.cpp
  Engine/ac/math.h
  Engine/script/script_api.h
Labels: ags3

#642 Plugin save/restore uses file handle.
  Common/util/filestream.h
  Engine/ac/game.cpp
  Engine/game/savegame_components.cpp
  Engine/plugin/agsplugin.cpp
  Engine/plugin/plugin_engine.h
  Plugins/AGSflashlight/agsflashlight.cpp
  Plugins/ags_parallax/ags_parallax.cpp
  Plugins/ags_snowrain/ags_snowrain.cpp
Labels: ags3

#619 Don't select layer objects when the room tab isn't the active tab
  Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
Labels: ags3, editor, pull: under review

#646 AGS3 plugin builtin refactor
  Engine/plugin/agsplugin.cpp
  Engine/plugin/plugin_builtin.h
  Engine/plugin/plugin_engine.h
  OSX/xcode/ags/plugin_registration.cpp
Labels: ags3

#643 SDL2: add agspalrender (or palgorithms) plugin.
  Android/library/jni/Android.mk
  Android/library/jni/Application.mk
  Engine/Makefile-objs
  Engine/plugin/agsplugin.cpp
  Plugins/agspalrender/Makefile
  Plugins/agspalrender/README.md
  Plugins/agspalrender/ags_palrender.cpp
  Plugins/agspalrender/agspalrender.h
  Plugins/agspalrender/agsplugin.h
  Plugins/agspalrender/palrender.h
  Plugins/agspalrender/raycast.cpp
  Plugins/agspalrender/raycast.h
Labels: ags3, backwards compatibility

#649 dynamicsprite.cpp: use adjusted filename
  Engine/ac/dynamicsprite.cpp
Labels: ags3

#650 global_translation: don't bother checking with plugin if 64bit
  Engine/ac/global_translation.cpp
Labels: ags3
