Repository adventuregamestudio/ags, pull requests merged in 2019-03, with the labels that each got.

#656 Script API: SkipCutscene and cutscene that cannot be skipped by user input
  Editor/AGS.Editor/Resources/agsdefns.sh
  Engine/ac/game.cpp
  Engine/ac/global_api.cpp
  Engine/ac/global_game.cpp
  Engine/ac/global_game.h
Labels: ags3, script api

#651 AGS 3: deprecate sprite resolution tag
  Common/ac/game_version.h
  Common/ac/gamestructdefines.h
  Common/game/main_game_file.cpp
  Editor/AGS.Editor/AGSEditor.cs
  Editor/AGS.Editor/ApplicationController.cs
  Editor/AGS.Editor/DataFileWriter.cs
  Editor/AGS.Editor/GUI/GUIController.cs
  Editor/AGS.Editor/ImportExport.cs
  Editor/AGS.Editor/NativeProxy.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs
  Editor/AGS.Editor/Panes/ViewPreview.cs
  Editor/AGS.Editor/Tasks.cs
  Editor/AGS.Editor/Utils/NativeConstants.cs
  Editor/AGS.Editor/Utils/Utilities.cs
  Editor/AGS.Native/NativeMethods.cpp
  Editor/AGS.Native/NativeMethods.h
  Editor/AGS.Native/agsnative.cpp
  Editor/AGS.Types/AGS.Types.csproj
  Editor/AGS.Types/Enums/SpriteImportResolution.cs
  Editor/AGS.Types/HelperTypes/SpriteInfo.cs
  Editor/AGS.Types/Sprite.cs
  Engine/ac/sprite.cpp
Labels: ags3, editor

#654 AGS 3: replace global font scale with individual setting
  Common/ac/game_version.h
  Common/ac/gamesetupstruct.cpp
  Common/ac/gamesetupstruct.h
  Common/ac/gamestructdefines.h
  Common/font/agsfontrenderer.h
  Common/font/fonts.cpp
  Common/font/fonts.h
  Common/font/ttffontrenderer.cpp
  Common/font/ttffontrenderer.h
  Common/font/wfnfontrenderer.cpp
  Common/font/wfnfontrenderer.h
  Common/game/main_game_file.cpp
  Editor/AGS.Editor/AGSEditor.cs
  Editor/AGS.Editor/Components/FontsComponent.cs
  Editor/AGS.Editor/DataFileWriter.cs
  Editor/AGS.Editor/Panes/FontEditor.cs
  Editor/AGS.Editor/Panes/GeneralSettingsPane.cs
  Editor/AGS.Editor/Tasks.cs
  Editor/AGS.Editor/Utils/NativeConstants.cs
  Editor/AGS.Native/NativeMethods.cpp
  Editor/AGS.Native/agsnative.cpp
  Editor/AGS.Types/Font.cs
  Editor/AGS.Types/Settings.cs
  Engine/ac/display.cpp
  Engine/game/game_init.cpp
  Engine/main/engine.cpp
  Engine/main/engine_setup.cpp
Labels: ags3, editor

#667 macos: Initial fixes to get macos building with Makefile
  Engine/Makefile
  Engine/Makefile-defs.linux
  Engine/Makefile-defs.osx
  Engine/Makefile-objs
  Engine/platform/osx/acplmac.cpp
  OSX/patches/allegro-4.4.2.patch
Labels: ags3

#652 AGS3 refactor ManagedObjectPool to address slow lookups
  Engine/ac/dynobj/cc_dynamicobject.cpp
  Engine/ac/dynobj/managedobjectpool.cpp
  Engine/ac/dynobj/managedobjectpool.h
  Engine/script/script_runtime.cpp
Labels: ags3

#672 AGS 3: deprecated "room resolution" and added MaskResolution property instead
  Common/ac/gamesetupstructbase.cpp
  Common/ac/gamesetupstructbase.h
  Common/game/room_file.cpp
  Common/game/room_version.h
  Common/game/roomstruct.cpp
  Common/game/roomstruct.h
  Common/gfx/bitmap.cpp
  Common/gfx/bitmap.h
  Editor/AGS.Editor/AGSEditor.cs
  Editor/AGS.Editor/Components/RoomsComponent.cs
  Editor/AGS.Editor/NativeProxy.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/BaseAreasEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/CharactersEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/EmptyEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomEditFilters/ObjectsEditorFilter.cs
  Editor/AGS.Editor/Panes/Room/RoomSettingsEditor.cs
  Editor/AGS.Editor/Tasks.cs
  Editor/AGS.Native/NativeMethods.cpp
  Editor/AGS.Native/NativeMethods.h
  Editor/AGS.Native/agsnative.cpp
  Editor/AGS.Types/AGS.Types.csproj
  Editor/AGS.Types/Enums/RoomResolution.cs
  Editor/AGS.Types/Game.cs
  Editor/AGS.Types/PropertyGridExtras/RoomMaskResolutionTypeConverter.cs
  Editor/AGS.Types/Room.cs
  Editor/AGS.Types/Settings.cs
  Engine/ac/draw.cpp
  Engine/ac/global_debug.cpp
  Engine/ac/room.cpp
Labels: ags3, editor

#673 AGS3: toojay's Linux OpenGL support with Glad
  Copyright.txt
  Engine/Makefile
  Engine/Makefile-defs.linux
  Engine/Makefile-defs.osx
  Engine/Makefile-objs
  Engine/ac/runtime_defines.h
  Engine/gfx/ali3dogl.cpp
  Engine/gfx/ali3dogl.h
  Engine/gfx/gfxdriverfactory.cpp
  Engine/gfx/gfxfilter_aaogl.cpp
  Engine/gfx/gfxfilter_ogl.cpp
  Engine/gfx/ogl_headers.h
  Engine/libsrc/glad/include/KHR/khrplatform.h
  Engine/libsrc/glad/include/glad/glad.h
  Engine/libsrc/glad/include/glad/glad_glx.h
  Engine/libsrc/glad/include/glad/glad_wgl.h
  Engine/libsrc/glad/src/glad.c
  Engine/libsrc/glad/src/glad_glx.c
  Engine/libsrc/glad/src/glad_wgl.c
  Engine/platform/base/agsplatformdriver.cpp
  Engine/platform/linux/acpllnx.cpp
  Solutions/Engine.App/Engine.App.vcxproj
  Solutions/Engine.App/Engine.App.vcxproj.filters
Labels: ags3

#681 AGS3 audio: introduce audio system headers
  Engine/ac/audiochannel.cpp
  Engine/ac/audioclip.cpp
  Engine/ac/character.cpp
  Engine/ac/characterinfo_engine.cpp
  Engine/ac/dialog.cpp
  Engine/ac/display.cpp
  Engine/ac/draw.cpp
  Engine/ac/dynobj/cc_audiochannel.cpp
  Engine/ac/event.cpp
  Engine/ac/game.cpp
  Engine/ac/gamestate.cpp
  Engine/ac/global_api.cpp
  Engine/ac/global_audio.cpp
  Engine/ac/global_game.cpp
  Engine/ac/global_video.cpp
  Engine/ac/global_viewframe.cpp
  Engine/ac/invwindow.cpp
  Engine/ac/room.cpp
  Engine/ac/sys_events.cpp
  Engine/ac/system.cpp
  Engine/ac/viewframe.cpp
  Engine/ac/walkbehind.cpp
  Engine/debug/debug.cpp
  Engine/game/game_init.cpp
  Engine/game/savegame.cpp
  Engine/game/savegame_components.cpp
  Engine/gui/cscidialog.cpp
  Engine/gui/mypushbutton.cpp
  Engine/main/config.cpp
  Engine/main/engine.cpp
  Engine/main/game_run.cpp
  Engine/main/game_start.cpp
  Engine/main/mainheader.h
  Engine/main/quit.cpp
  Engine/main/update.cpp
  Engine/media/audio/audio_system.h
  Engine/media/video/video.cpp
  Engine/platform/osx/acplmac.cpp
  Engine/platform/windows/acplwin.cpp
  Engine/platform/windows/media/video/acwavi3d.cpp
  Engine/plugin/agsplugin.cpp
  Engine/script/script.cpp
Labels: ags3

#680 AGS3 mp3/ogg decoder: fix small lib bug.
  Engine/libsrc/almp3/almp3.c
  Engine/libsrc/alogg/alogg.c
Labels: ags3

#679 AGS3: Make fps display stable and make timing workable when maxed-framerate
  Engine/ac/display.cpp
  Engine/ac/draw.cpp
  Engine/ac/game.cpp
  Engine/ac/game.h
  Engine/ac/global_game.cpp
  Engine/ac/room.cpp
  Engine/game/savegame_components.cpp
  Engine/main/game_run.cpp
  Engine/main/update.cpp
  Engine/media/audio/audio.cpp
Labels: ags3

#684 AGS3 audio: remove last_sound_played and soundclip->restart()
  Engine/ac/global_audio.cpp
  Engine/main/engine.cpp
  Engine/media/audio/audio.cpp
  Engine/media/audio/audio.h
  Engine/media/audio/clip_mydumbmod.cpp
  Engine/media/audio/clip_mydumbmod.h
  Engine/media/audio/clip_myjgmod.cpp
  Engine/media/audio/clip_myjgmod.h
  Engine/media/audio/clip_mymidi.cpp
  Engine/media/audio/clip_mymidi.h
  Engine/media/audio/clip_mymp3.cpp
  Engine/media/audio/clip_mymp3.h
  Engine/media/audio/clip_myogg.cpp
  Engine/media/audio/clip_myogg.h
  Engine/media/audio/clip_mystaticmp3.cpp
  Engine/media/audio/clip_mystaticmp3.h
  Engine/media/audio/clip_mystaticogg.cpp
  Engine/media/audio/clip_mystaticogg.h
  Engine/media/audio/clip_mywave.cpp
  Engine/media/audio/clip_mywave.h
  Engine/media/audio/soundclip.h
Labels: ags3

#685 Timing: use c++ std timers instead of maintaining own timer thread.
  Engine/ac/character.cpp
  Engine/ac/characterinfo_engine.cpp
  Engine/ac/dialog.cpp
  Engine/ac/display.cpp
  Engine/ac/draw.cpp
  Engine/ac/event.cpp
  Engine/ac/game.cpp
  Engine/ac/gamestate.cpp
  Engine/ac/gamestate.h
  Engine/ac/global_audio.cpp
  Engine/ac/global_game.cpp
  Engine/ac/invwindow.cpp
  Engine/ac/sys_events.cpp
  Engine/ac/timer.cpp
  Engine/ac/timer.h
  Engine/debug/debug.cpp
  Engine/debug/debugger.h
  Engine/debug/filebasedagsdebugger.cpp
  Engine/game/savegame.cpp
  Engine/gfx/ali3dogl.cpp
  Engine/gfx/ali3dsw.cpp
  Engine/gfx/gfxdriverbase.cpp
  Engine/gfx/gfxdriverbase.h
  Engine/gui/cscidialog.cpp
  Engine/gui/mypushbutton.cpp
  Engine/main/engine.cpp
  Engine/main/game_run.cpp
  Engine/main/game_start.cpp
  Engine/main/graphics_mode.cpp
  Engine/main/update.cpp
  Engine/media/audio/audio.cpp
  Engine/media/audio/audio.h
  Engine/media/video/video.cpp
  Engine/platform/base/agsplatformdriver.cpp
  Engine/platform/linux/acpllnx.cpp
  Engine/platform/osx/acplmac.cpp
  Engine/platform/windows/acplwin.cpp
  Engine/platform/windows/gfx/ali3dd3d.cpp
  Engine/platform/windows/media/video/acwavi.cpp
  Engine/platform/windows/media/video/acwavi3d.cpp
Labels: ags3

#689 AGS 3: cherry picked and tidied mgambrell's AudioChannelsLocks commit
  Engine/ac/audiochannel.cpp
  Engine/ac/audioclip.cpp
  Engine/ac/game.cpp
  Engine/ac/global_audio.cpp
  Engine/ac/system.cpp
  Engine/ac/viewframe.cpp
  Engine/game/savegame.cpp
  Engine/game/savegame_components.cpp
  Engine/main/update.cpp
  Engine/media/audio/ambientsound.cpp
  Engine/media/audio/audio.cpp
  Engine/media/audio/audio.h
  Engine/media/audio/clip_myogg.cpp
  Engine/media/audio/clip_mystaticogg.cpp
  Engine/media/audio/clip_mywave.cpp
  Engine/media/audio/soundclip.cpp
  Engine/media/audio/soundclip.h
  Engine/plugin/agsplugin.cpp
  Solutions/Engine.App/Engine.App.vcxproj
  Solutions/Engine.App/Engine.App.vcxproj.filters
Labels: ags3, multithreaded audio, pull: under review

#692 AGS3 - miscellaneous fixes
  Engine/ac/draw.cpp
  Engine/ac/timer.cpp
  Engine/debug/debug.cpp
  Engine/main/game_run.cpp
  Engine/platform/base/agsplatformdriver.cpp
  Engine/platform/base/agsplatformdriver.h
  Engine/platform/linux/acpllnx.cpp
  Engine/platform/osx/acplmac.cpp
  Engine/platform/windows/acplwin.cpp
Labels: ags3, bug
