Repository adventuregamestudio/ags, pull requests merged in 2020-01, with the labels that each got.

#1001 Modifies palrender plugin for leaner agsplugin.h
  Plugins/agspalrender/ags_palrender.cpp
Labels: ags 4, pull: under review

#1028 Engine: allow to quit from max framerate mode (2)
  Engine/ac/draw.cpp
  Engine/ac/game.cpp
  Engine/ac/game.h
  Engine/ac/global_debug.cpp
  Engine/ac/global_game.cpp
  Engine/ac/timer.cpp
  Engine/ac/timer.h
  Engine/debug/debug.cpp
  Engine/debug/debugger.h
  Engine/main/game_run.cpp
  Engine/main/game_run.h
  Engine/main/main.cpp
Labels: pull: reviewed

#1018 Automatic font outlines (2)
  Common/ac/game_version.h
  Common/ac/gamesetupstruct.cpp
  Common/ac/gamestructdefines.h
  Common/font/fonts.cpp
  Common/font/fonts.h
  Common/game/main_game_file.cpp
  Common/gfx/allegrobitmap.cpp
  Common/gfx/allegrobitmap.h
  Editor/AGS.Editor/AGSEditor.cs
  Editor/AGS.Editor/DataFileWriter.cs
  Editor/AGS.Editor/Tasks.cs
  Editor/AGS.Types/AGS.Types.csproj
  Editor/AGS.Types/Enums/FontAutoOutlineStyle.cs
  Editor/AGS.Types/Font.cs
  Engine/ac/display.cpp
  Engine/ac/display.h
  Engine/gfx/blender.cpp
  Engine/gfx/blender.h
Labels: pull: under review

#942 Script API: changed Object.SetView default loop & frame values to 0
  Common/ac/gamestructdefines.h
  Editor/AGS.Editor/Resources/agsdefns.sh
  Engine/ac/global_object.cpp
  Engine/ac/object.cpp
Labels: context: script api, pull: postponed, pull: under review, type: enhancement

#1031 Script API: get DrawingSurface for the room masks
  Common/game/roomstruct.cpp
  Common/game/roomstruct.h
  Editor/AGS.Editor/Resources/agsdefns.sh
  Editor/AGS.Native/agsnative.cpp
  Editor/AGS.Types/Enums/ScriptAPIVersion.cs
  Engine/ac/drawingsurface.cpp
  Engine/ac/dynobj/scriptdrawingsurface.cpp
  Engine/ac/dynobj/scriptdrawingsurface.h
  Engine/ac/global_api.cpp
  Engine/ac/global_hotspot.cpp
  Engine/ac/global_hotspot.h
  Engine/ac/global_region.cpp
  Engine/ac/global_region.h
  Engine/ac/global_walkablearea.cpp
  Engine/ac/global_walkablearea.h
  Engine/ac/hotspot.cpp
  Engine/ac/hotspot.h
  Engine/ac/region.cpp
  Engine/ac/room.cpp
  Engine/ac/room.h
Labels: context: script api, pull: under review

#1032 iOS Scale Fix
  Engine/gfx/ali3dogl.cpp
  Engine/gfx/ogl_headers.h
  iOS/xcode/ags/Classes/EAGLView.m
  iOS/xcode/ags/Classes/agsViewController.mm
  version.json
Labels: pull: under review, system: ios

#1036 Tab switching performance improvements
  Editor/AGS.Editor/ColorThemes/Controls/ComboBoxCustom.cs
  Editor/AGS.Editor/Panes/ScriptEditor.cs
Labels: pull: under review
