Repository adventuregamestudio/ags, pull requests merged in 2021-04, with the labels that each got.

#1248 3.5.1 Editor: implemented Settings.AttachDataToExe
  Editor/AGS.Editor/AGSEditor.cs
  Editor/AGS.Editor/BuildTargets/BuildTargetDebug.cs
  Editor/AGS.Editor/BuildTargets/BuildTargetWindows.cs
  Editor/AGS.Types/AudioClip.cs
  Editor/AGS.Types/AudioClipFolder.cs
  Editor/AGS.Types/Enums/AudioFileBundlingType.cs
  Editor/AGS.Types/Settings.cs
Labels: pull: under review

#1252 Engine: implemented command line options for config and user dir paths
  Engine/main/main.cpp
Labels: pull: under review

#1256 New compiler: `.Length` pseudo-attribute for dynamic arrays
  Compiler/script2/cs_parser.cpp
  Compiler/script2/cs_parser.h
  Compiler/test2/cc_bytecode_test_1.cpp
  Compiler/test2/cc_parser_test_1.cpp
  Engine/ac/dynobj/cc_dynamicarray.cpp
  Engine/script/exports.cpp
Labels: ags 4, context: script compiler, pull: under review

#1261 3.5.1: Added System.SaveConfigToFile() and support $CONFIGFILE$ scriptpath
  Common/util/directory.cpp
  Editor/AGS.Editor/Resources/agsdefns.sh
  Engine/ac/file.cpp
  Engine/ac/global_game.cpp
  Engine/ac/system.cpp
  Engine/main/config.cpp
  Engine/main/quit.cpp
Labels: pull: under review

#1260 Improve argument print in DumpInstruction
  Engine/script/cc_instance.cpp
  Engine/script/systemimports.cpp
  Engine/script/systemimports.h
Labels: pull: under review

#1250 New compiler: Compile-time expressions, `++` and `--` operators, `readonly` parameters
  Compiler/script2/cc_compiledscript.cpp
  Compiler/script2/cc_compiledscript.h
  Compiler/script2/cc_internallist.cpp
  Compiler/script2/cc_internallist.h
  Compiler/script2/cc_symboltable.cpp
  Compiler/script2/cc_symboltable.h
  Compiler/script2/cs_compile_time.cpp
  Compiler/script2/cs_compile_time.h
  Compiler/script2/cs_parser.cpp
  Compiler/script2/cs_parser.h
  Compiler/test2/cc_bytecode_test_0.cpp
  Compiler/test2/cc_bytecode_test_1.cpp
  Compiler/test2/cc_parser_test_0.cpp
  Compiler/test2/cc_parser_test_1.cpp
  Compiler/test2/cc_symboltable_test.cpp
  Solutions/Compiler2.Lib/Compiler2.Lib.vcxproj
  Solutions/Compiler2.Lib/Compiler2.Lib.vcxproj.filters
Labels: ags 4, pull: under review
