Repository adventuregamestudio/ags, pull requests merged in 2021-01, with the labels that each got.

#1160 Implement --tell-gameproperties instead of putting game info in --tell-config
  Engine/main/engine.cpp
  Engine/main/main.cpp
  Engine/platform/windows/setup/winsetup.cpp
Labels: ags3, pull: under review

#1161 Editor: replace DeserializeIgnoreAttribute with [Obsolete] properties
  Editor/AGS.Types/AGS.Types.csproj
  Editor/AGS.Types/Attributes/DeserializeIgnoreAttribute.cs
  Editor/AGS.Types/DialogOption.cs
  Editor/AGS.Types/SerializeUtils.cs
  Editor/AGS.Types/Settings.cs
Labels: pull: under review

#1159 AGS3 SDL2: Debian fixes to produce AGS Linux Package
  .cirrus.yml
  CMake/FetchSDL2.cmake
  CMake/FindLocalOpenAL.cmake
  Editor/AGS.Editor/BuildTargets/BuildTargetLinux.cs
  ci/linux/Dockerfile
  debian/ags+libraries/hooks/B00_copy_libs.sh
  debian/control
  debian/copyright
  debian/rules
Labels: pull: under review

#1165 SDL2 Port: building instructions
  Solutions/Common.Lib/Common.Lib.vcxproj
  Solutions/Engine.App/Engine.App.vcxproj
  Solutions/directx.props
  Windows/README.md
  debian/README.md
Labels: ags3, backend: sdl2, pull: under review

#1183 AGS 4: extended meta format for main game data
  Common/game/main_game_file.cpp
  Common/game/main_game_file.h
  Common/game/room_file.cpp
  Editor/AGS.Editor/DataFileWriter.cs
Labels: ags 4, context: game files, pull: under review

#1182 When user interface is disabled, only grey/black out GUI buttons that have an associated click action.
  Common/gui/guibutton.cpp
Labels: pull: under review
