Repository adventuregamestudio/ags, pull requests merged in 2021-07, with the labels that each got.

#1330 Engine: support scripts as separate assets
  Common/game/main_game_file.cpp
  Common/game/main_game_file.h
  Engine/ac/room.cpp
  Engine/game/game_init.cpp
  Engine/game/game_init.h
  Engine/main/game_file.cpp
Labels: ags3, context: game files, pull: under review

#1321 Partial Unicode support in the engine (UTF-8 translations)
  Common/ac/keycode.h
  Common/font/fonts.cpp
  Common/game/tra_file.cpp
  Common/game/tra_file.h
  Common/gui/guiobject.h
  Common/gui/guitextbox.cpp
  Common/gui/guitextbox.h
  Common/util/string.cpp
  Common/util/string.h
  Common/util/string_utils.cpp
  Common/util/string_utils.h
  Editor/AGS.Editor/Components/TranslationsComponent.cs
  Editor/AGS.Editor/DataFileWriter.cs
  Editor/AGS.Editor/NativeProxy.cs
  Editor/AGS.Native/NativeMethods.cpp
  Editor/AGS.Native/NativeMethods.h
  Editor/AGS.Native/agsnative.cpp
  Editor/AGS.Types/Translation.cs
  Engine/ac/dialog.cpp
  Engine/ac/display.cpp
  Engine/ac/invwindow.cpp
  Engine/ac/string.cpp
  Engine/ac/sys_events.cpp
  Engine/ac/sys_events.h
  Engine/ac/translation.cpp
  Engine/gui/cscidialog.cpp
  Engine/main/engine.cpp
  Engine/main/game_run.cpp
  Engine/main/game_run.h
  Engine/main/main.cpp
  Engine/media/video/video.cpp
  Engine/plugin/agsplugin.cpp
  Tools/data/tra_utils.cpp
  libsrc/allegro/include/allegro/unicode.h
  libsrc/allegro/src/file.c
  libsrc/allegro/src/unicode.c
  libsrc/allegro/src/unix/ufile.c
  libsrc/allegro/src/win/wfile.c
Labels: ags3, context: unicode, pull: under review

#1350 ci_find_file/unix: add fast-path for file lookup
  Common/util/misc.cpp
Labels: pull: under review

#1351 import error: print all missing imports for current script module
  Engine/script/cc_instance.cpp
Labels: pull: under review

#1348 Tools: agspak, agsunpak - pack and unpack game packages (and templates)
  Common/util/directory.cpp
  Common/util/directory.h
  Common/util/multifilelib.h
  Common/util/mutifilelib.cpp
  Common/util/path.cpp
  Common/util/path.h
  Common/util/stream.cpp
  Common/util/stream.h
  Solutions/Tools.App/agspak.vcxproj
  Solutions/Tools.App/agspak.vcxproj.filters
  Solutions/Tools.App/agsunpak.vcxproj
  Solutions/Tools.App/agsunpak.vcxproj.filters
  Solutions/Tools.sln
  Tools/agspak/Makefile
  Tools/agspak/main.cpp
  Tools/agsunpak/Makefile
  Tools/agsunpak/main.cpp
  Tools/data/mfl_utils.cpp
  Tools/data/mfl_utils.h
Labels: ags3, pull: under review

#1372 3.6.0: Support reading from game assets in script + Editor supports packing custom files
  Common/core/assetmanager.cpp
  Common/core/assetmanager.h
  Common/gfx/allegrobitmap.cpp
  Common/gfx/allegrobitmap.h
  Common/gfx/bitmap.cpp
  Common/gfx/bitmap.h
  Editor/AGS.Editor/AGSEditor.cs
  Editor/AGS.Editor/BuildTargets/BuildTargetDataFile.cs
  Editor/AGS.Editor/Components/SpeechComponent.cs
  Editor/AGS.Editor/DataFileWriter.cs
  Editor/AGS.Editor/Utils/Utilities.cs
  Editor/AGS.Types/Settings.cs
  Engine/ac/file.cpp
  Engine/ac/global_dynamicsprite.cpp
  Engine/ac/global_file.cpp
  Engine/ac/listbox.cpp
  Engine/ac/path_helper.h
Labels: context: game building, context: game files, context: script api, pull: under review
