Repository adventuregamestudio/ags, pull requests merged in 2022-06, with the labels that each got.

#1673 AGS 4: new compiler: replaced char* with const char* where necessary
  Compiler/script2/cc_symboltable.h
  Compiler/test2/cc_bytecode_test_0.cpp
  Compiler/test2/cc_bytecode_test_1.cpp
  Compiler/test2/cc_bytecode_test_lib.cpp
  Compiler/test2/cc_bytecode_test_lib.h
  Compiler/test2/cc_parser_test_0.cpp
  Compiler/test2/cc_parser_test_1.cpp
  Compiler/test2/cc_scanner_test.cpp
Labels: ags 4

#1680 3.6.0: don't store script object pointers in the game objects
  Engine/ac/gamestate.cpp
  Engine/ac/gamestate.h
  Engine/ac/overlay.cpp
  Engine/ac/speech.cpp
Labels: context: code

#1693 Editor: added Help command for pane's tab context menu
  Editor/AGS.Editor/GUI/TabbedDocumentManager.cs
Labels: what: editor, context: ui/ux

#1697 Tidy Library classes
  Engine/platform/windows/gfx/ali3dd3d.cpp
  Engine/plugin/agsplugin.cpp
  Engine/util/library.h
  Engine/util/library_dummy.h
  Engine/util/library_posix.h
  Engine/util/library_windows.h
Labels: context: code

#1675 AGS 4: new compiler: fixed int32 limit tests
  Compiler/test2/cc_parser_test_0.cpp
  Compiler/test2/cc_scanner_test.cpp
Labels: ags 4, context: script compiler

#1710 Android: add credits
  Android/library/runtime/src/main/res/layout/credits.xml
  Android/library/runtime/src/main/res/values/strings.xml
Labels: system: android

#1718 CMake: debug defines only set per external config
  CMakeLists.txt
  Common/CMakeLists.txt
  Common/ac/spritecache.cpp
  Common/core/platform.h
  Engine/CMakeLists.txt
  Engine/ac/dynobj/cc_dynamicobject.cpp
  Engine/ac/dynobj/managedobjectpool.h
  Engine/debug/debug.cpp
Labels: context: code

#1722 Cleanup make/compilation flags and library patches
  CMake/CheckLoadMidiPf.cmake
  CMake/FetchAllegro.cmake
  CMake/FindAllegro.cmake
  CMake/FindLocalAllegro.cmake
  CMakeLists.txt
  Common/CMakeLists.txt
  Editor/AGS.Native/NativeDLL.vcxproj
  Editor/Native/acfonts_agsnative.cpp
  Engine/Makefile-defs.linux
  Engine/Makefile-defs.osx
  OSX/patches/allegro-4.4.2.patch
  OSX/patches/dumb-0.9.3.patch
  Solutions/Common.Lib/Common.Lib.vcxproj
  Solutions/Compiler.App/Compiler.App.vcxproj
  Solutions/Compiler.Lib/Compiler.Lib.Test.vcxproj
  Solutions/Compiler.Lib/Compiler.Lib.vcxproj
  Solutions/Engine.App/Engine.App.vcxproj
Labels: context: code
