Repository adventuregamestudio/ags, pull requests merged in 2023-06, with the labels that each got.

#2011 Script API: implemented ScriptName and Type.GetByName() for all applicable types.
  Editor/AGS.Editor/Resources/agsdefns.sh
  Engine/ac/audioclip.cpp
  Engine/ac/character.cpp
  Engine/ac/dialog.cpp
  Engine/ac/gui.cpp
  Engine/ac/guicontrol.cpp
  Engine/ac/hotspot.cpp
  Engine/ac/inventoryitem.cpp
  Engine/ac/object.cpp
  Engine/script/script_runtime.cpp
  Engine/script/script_runtime.h
Labels: type: enhancement, context: script api

#2012 Script API: implement eEventGameSaved
  Editor/AGS.Editor/Resources/agsdefns.sh
  Engine/ac/event.h
  Engine/ac/game.cpp
Labels: type: enhancement, context: script api

#2021 Explicitly search for plugins in a game's data dir
  Engine/main/main.cpp
  Engine/plugin/agsplugin.cpp
  Engine/util/library.h
  Engine/util/library_dummy.h
  Engine/util/library_posix.h
  Engine/util/library_windows.h
Labels: type: enhancement, context: game files

#2014 Editor: reimplement SpriteSelector's multiple sprite properties editing
  Editor/AGS.Editor/GUI/GUIController.cs
  Editor/AGS.Editor/Panes/SpriteManager.cs
  Editor/AGS.Editor/Panes/SpriteSelector.Designer.cs
  Editor/AGS.Editor/Panes/SpriteSelector.cs
Labels: type: bug, what: editor, context: ui/ux, context: performance

#2023 Adjust automatic layout of some panes (for 100% and 200% scaling)
  Editor/AGS.Editor/Panes/InventoryEditor.Designer.cs
  Editor/AGS.Editor/Panes/InventoryEditor.cs
  Editor/AGS.Editor/Panes/SpriteSelector.Designer.cs
  Editor/AGS.Editor/Panes/SpriteSelector.cs
Labels: type: enhancement, what: editor, context: ui/ux

#2041 Engine: remember overlay index and try it before looking again
  Engine/ac/overlay.cpp
Labels: context: performance

#2036 Editor: export sprites asynchronously with progress count
  Editor/AGS.Editor/Panes/SpriteSelector.cs
  Editor/AGS.Editor/Tasks.cs
  Editor/AGS.Editor/Utils/SpriteTools.cs
  Editor/AGS.Types/Interfaces/ISpriteFolder.cs
  Editor/AGS.Types/SpriteFolder.cs
Labels: what: editor, context: ui/ux

#2048 3.6.1: improve ScreenOverlays storage performance
  Engine/ac/character.cpp
  Engine/ac/display.cpp
  Engine/ac/draw.cpp
  Engine/ac/dynobj/scriptoverlay.cpp
  Engine/ac/game.cpp
  Engine/ac/global_character.cpp
  Engine/ac/global_overlay.cpp
  Engine/ac/overlay.cpp
  Engine/ac/overlay.h
  Engine/ac/room.cpp
  Engine/ac/runtime_defines.h
  Engine/ac/screenoverlay.h
  Engine/game/savegame.cpp
  Engine/game/savegame_components.cpp
  Engine/game/savegame_v321.cpp
  Engine/main/update.cpp
Labels: context: performance

#2044 Extend Right-to-left text render for GUI and non-wrapping DrawString
  Common/ac/game_version.h
  Common/game/main_game_file.cpp
  Common/gui/guibutton.cpp
  Common/gui/guidefines.h
  Common/gui/guilabel.cpp
  Common/gui/guilabel.h
  Common/gui/guimain.h
  Common/gui/guitextbox.h
  Editor/AGS.Editor/AGSEditor.cs
  Editor/AGS.Editor/DataFileWriter.cs
  Editor/AGS.Editor/Tasks.cs
  Editor/AGS.Types/GUIControl.cs
  Editor/AGS.Types/GUIListBox.cs
  Editor/Native/acgui_agsnative.cpp
  Engine/ac/drawingsurface.cpp
  Engine/ac/string.cpp
  Engine/ac/string.h
  Engine/gui/gui_engine.cpp
Labels: type: enhancement, context: translations
